### PR TITLE
Fix migration deadlock 

### LINKED ISSUE #7: wasp-app-runner gets stuck on migrations if we need to create a new migration file
In our `starter` templates we purposely exclude `/migrations` folder from the templates.
The reasoning is so that the user isn't locked into a single database (`migration_lock.toml`).

Running `wasp db migrate-dev` when a new migration file needs to created, you are prompted to enter the name of the migration file. Since we don't handle that case, `wasp-app-runner` gets stuck waiting for a migration name, leading to timeouts in headless tests.

Related: https://github.com/wasp-lang/wasp/issues/2833

### PR DESCRIPTION
**Pull request by FranjoMindek**
Fixes: https://github.com/wasp-lang/runner-action/issues/7

### CODE REVIEW

File: src/waspCli.ts [hunk 1]
```diff
@@ -20,7 +20,9 @@ export function waspMigrateDb({
   return spawnWithLog({
     name: "wasp-migrate-db",
     cmd: waspCliCmd,
-    args: ["db", "migrate-dev"],
+    // We use --name flag to ensure the commands succeeds even if there are migration files missing.
+    // The name is already timestamped by prisma, so we don't need to do it ourselves.
+    args: ["db", "migrate-dev", "--name", "auto-migration"],
```
Comment (infomiho) [inline src/waspCli.ts]: I'd include more of the reasoning from the issue in the comment "sometimes we test stuff without migrations dir, so Prisma will ask for a migration name, this causes the runner to wait for input indefinitely" something along those lines.

Comment (FranjoMindek) [reply src/waspCli.ts]: Made it a bit more verbose and followed above:

```ts
export function waspMigrateDb({
  waspCliCmd,
  pathToApp,
  extraEnv,
}: {
  waspCliCmd: WaspCliCmd;
  pathToApp: PathToApp;
  extraEnv: EnvVars;
}): Promise<{ exitCode: number | null }> {
  return spawnWithLog({
    name: "wasp-migrate-db",
    cmd: waspCliCmd,
    /**
     * We use the --name flag because sometimes we run apps without a migrations directory,
     * which causes Prisma to prompt for a migration name interactively. This would make
     * the runner wait for input indefinitely.
     * Prisma timestamps all migration filenames automatically.
     * See: https://github.com/wasp-lang/runner-action/issues/7
     */
    args: ["db", "migrate-dev", "--name", "auto-migration"],
    cwd: pathToApp,
    extraEnv,
  });
}
```

**Review by infomiho — APPROVED** [review]
Good to go
